export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_ANNOUNCEMENTS = "GET_ALL_ANNOUNCEMENTS";
export const DELETE_USER = "DELETE_USER";
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";