export const GET_USER_ORDERS = 'GET_USER_ORDERS';
export const GET_ORDERS_TO_USER = 'GET_ORDERS_TO_USER';
export const POST_ORDER = 'POST_ORDER';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS'