export const GET_FAVOURITE = 'GET_FAVOURITE';
export const GET_FAVOURITE_ID = 'GET_FAVOURITE_ID';
export const ADD_ANNOUNCEMENT_FAVOURITE = 'ADD_ANNOUNCEMENT_FAVOURITE';
export const DELETE_FAVOURITE = "DELETE_FAVOURITE";
