export const POST_USER = 'POST_USER';
export const POST_SIGN_IN = 'POST_SIGN_IN';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';
export const GET_OWNER_ID = 'GET_USER_ID';
export const USER_AUTH_REQUEST = "USER_AUTH_REQUEST";
export const USER_AUTH_FAILED = "USER_AUTH_FAILED";
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";